############# Slovak navigation ##############

# main menu
[[main]]
name = "Naša kampaň"
url = "/"
weight = 1

[[main]]
name = "Naša štúdia"
url = "/#study"
weight = 2

[[main]]
name = "O nás"
url = "/#about"
weight = 3

[[main]]
name = "Kontaktujte nás"
url = "mailto:justine@regleselementaires.com"
weight = 4