############# French navigation ##############

# main menu
[[main]]
name = "Notre campagne"
url = "/"
weight = 1

[[main]]
name = "Notre étude"
url = "/#study"
weight = 2

[[main]]
name = "À propos"
url = "/#about"
weight = 3

[[main]]
name = "Contactez-nous"
url = "mailto:contact@regleselementaires.com"
weight = 4